version: '3'
services:
  postgres:
    image: "postgres"
    networks:
      - pgnet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=onerent
      - POSTGRES_PASSWORD=mysecretpassword
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - pgnet
    ports:
      - 8092:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin
networks:
  pgnet:

