INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), '"""Bike & Bed"" CharinCo Hostel"');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'hostel.name');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), '& And Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), '&And Hostel Ueno');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), '&And Hostel Akihabara');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), '&And Hostel-Asakusa North-');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), '328 Hostel & Lounge');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), '1night1980hostel Tokyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), '36Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Ace Inn Shinjuku');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), '3Q House - Asakusa Smile');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Air Osaka Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Akihabara Hotel 3000');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Aizuya Inn');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Almond hostel & cafe Shibuya');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Anne Hostel Yokozuna');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Anne Hostel Asakusabashi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Ark Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'AS House (Asakusa Smile)');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'ARTnSHELTER');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Asakusa Hostel Toukaisou');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Asakusahotel Wasou');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Asakusa Ryokan Toukaisou');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Astro Station');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Backpackers Hostel K''s House Hiroshima');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'B&S Eco Cube Shinsaibashi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Backpackers Hostel K''s House Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Backpackers Hotel Toyo Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Backpackers Hostel K''s House Tokyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Backstage Osaka Hostel & Bar');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Bed Stock');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Beagle Tokyo Hostel & Apartments');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Beehive Hostel Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Bird Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Bigtree Guesthouse');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'bnb+ Ninja Dojo Ueno');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Bonfire Hostel Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'bnb+Shinjuku Castle');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Bonsai Guest House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Book And Bed Tokyo Asakusa');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Book and Bed Tokyo - Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Book And Bed Tokyo Fukuoka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Bunka Hostel Tokyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Book And Bed Tokyo Ikebukuro');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Calendar Hotel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Capsule Hotel Anshin Oyado Shinbashi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Capsule Hotel Anshin Oyado Akihabara');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Capsule Hotel Asahi Plaza Shinsaibashi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Capsule Resort Kyoto Square');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Capsule Inn Kinshichou');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Capsule Value Kanda');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Centurion Cabin & Spa Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Casa Macondo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Centurion Hotel Residential Akasaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Chaganjutei');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Centurion Ladies Hostel Uenopark (Female only)');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'CITAN Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Colours');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Coco Hostel Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Comics & CapsuleHotel COMICAP kyotoshinkyogoku');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Daikoku Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Common de Hostel & Bar');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Dotombori Base');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Drop Inn Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Downtown Inn Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Edo Tokyo Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'ENAKA Asakusa Central Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Emblem Hostel Nishiarai');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Ezstay Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Family & bAKpAK Tokyo Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Fairfield House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Friends Kyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Fukuoka Backpackers Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'FUJITAYA Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Fukuoka Hana Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Gion Ryokan Q-beh');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Funtoco Backpackers Namba');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Goen Lounge＆Stay');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Gojo Guesthouse - Annex');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Gojo Guest House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Good Diner Inn Copain');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Grids Kyoto Shijo Kawaramachi Hotel & Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'GRIDS TOKYO AKIHABARA HOTEL&HOSTEL');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Grids Tokyo Asakusa-Bashi Hotel&Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'GRIDS TOKYO NIHOMBASHI EAST HOTEL&HOSTEL');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Bola-Bola');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Com Inn Hiroshima');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Denchi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Ga-Jyun');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Hachi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Hitsuji-An');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Hokorobi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Kaine');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Kyoto Inn');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House La Kongo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Matsu');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House ODORI');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Onoya');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Renjishi Kabuki');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Roku');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Shinagawa-shuku Tokyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Shiori Ann');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House TRACE');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House Yahata');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guest House YULULU');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse Fete');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse Fujitatami');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse Gloire');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse HetoGep');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse Hiroshima Mange Tak');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse Kagaribi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse Morizou Female only');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse Origami');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse SAI');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse Sensu');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse Shitamachi-Kujo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse Soi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Guesthouse U-En');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Harborside Guest House MINATO');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'HARUYA Hostels Aqua');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'HATAGO tenjin');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hikari House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hiromas Hostel in Akiba');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hiromas Hostel in Kanda');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hiromas Inn  Chitose-Karasuyama');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hiroshima Hana Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hiroshima Hostel EN');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hisayo''s Inn');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Home Hostel Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Homeikan');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hop Step Inn');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel & Cafe Bar Backpackers Miyajima');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel 64 Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel bedgasm');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Bushi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Chapter Two Tokyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Chillout');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'hostel DEN');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Ebi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Ebisutei Souzou with Sake Bar');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Enisia Namba');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Ginkakuji');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel HARUYA Book');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel HARUYA Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'HOSTEL HYAKU');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel J Culture 168');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Jin');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Kyoto Kizuna');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel LnK (Lodging & Kin)');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Mallika');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Mitsuwaya Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel moku-moku');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Mundo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Mundo Chiquito');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Namba Takumi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Pumpkey Tokyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Q');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Rakutsuki');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Stand By Me');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel Teltel Bouzu');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel TOKI');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel WAQWAQ Tokyo Ueno Asakusa');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'HOSTEL WASABI Kyoto Machiya Soba');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'HOSTEL WASABI Osaka Bed with Library');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hostel＆Café East57 Asakusabashi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel Cargo Shinsaibashi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel Chuo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel Graphy Nezu');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel Kawase Tokyo and Capsule');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel Mikado');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel Raizan South');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel Shin-Imamiya');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel Sun Plaza');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel Taiyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel Wako');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Hotel&Hostel On the Marks Tokyo Kawasaki');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Idocoro');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Ikidane House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Ikidane House Asakusa Hatago');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Ikidane House Namba');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Ikoi-no-Ie Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'iloha Hostel Namba Shinsaibashi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'IM Guest House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Imano Kyoto Kiyomizu Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Imano Tokyo Ginza Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Imano Tokyo Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'IRORI Nihonbashi Hostel and Kitchen');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Iza Tokyo Asakusa Guesthouse');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'J-Hoppers Hiroshima Guesthouse');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'J-Hoppers Kyoto Guest House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'J-Hoppers Osaka Guesthouse');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'J-Hoppers Osaka Universal');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'J''s Backpackers');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Jam Hostel Kyoto Gion');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Japanize Guest House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'JGH Tokyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Jimbocho Sakura Hotel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Jiyujin');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Juyoh Hotel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kaisu Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kaneyoshi Ryokan, Namba Dotombori');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Ken''s House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Khaosan Kyoto Guest House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Khaosan Tokyo Kabuki');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Khaosan Tokyo Laboratory');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Khaosan Tokyo Origami');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Khaosan Tokyo Samurai');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Khaosan World Asakusa RYOKAN & HOSTEL');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Khaosan World Namba');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Khaosan World Ryogoku Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Khaosan World Tennoji Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kia Ora Budgetstay');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kintetsu Friendly Hostel -Osaka Tennoji Park-');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Koenji Junjo Hotel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kyo To');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kyoto Be Open Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kyoto Guesthouse Roujiya');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kyoto Hana Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kyoto Hostel ZEN');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kyoto Morris Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kyoto Station Base');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kyoto Tsukiusagi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kyoto UTANO Youth Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Kyoubashi Ryokan');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Len Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Little Japan');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Lore Hostel Dontonbori');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Lucky''s');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Lyuro Tokyo Kiyosumi -The Share Hotels-');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'montan HAKATA');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Mosaic Hostel Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Mosaic Machiya KSK');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Music Uni Street Backpackers Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'MyCUBE by MYSTAYS Asakusa-Kuramae');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Nadeshiko Hotel Shibuya (Female Only)');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Nagomi-Ryokan Yuu');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Nihonbashi Muromachi BAY HOTEL');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Norishico Auto Guesthouse');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Nui. Hostel & Bar Lounge');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'O-yado Sato');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Oak Hostel Zen');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Oak Hotel Edo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Oakhostel Cabin');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Oakhostel Fuji');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Oakhostel Sakura');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Obi Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Okara Guesthouse');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'OKI''s Inn');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Omotenashi Hostel Miyajima');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka Fuku Hostel Nagomi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka Fuku Hostel Namba');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka Guest House Midoriya');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka Guesthouse Hive');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka GuestHouse KOMA');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka Guesthouse Nest');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka Guesthouse Sakura');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka Guesthouse SUN');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka Hana Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka Hostel Kai');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka International Youth Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Osaka Namba Hostel MIYABI');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Oshiteruya');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Peace House Abeno');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Peace House Sachi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Peace House Sakura');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Peace House Showa');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Peace House Suzunami');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Picnic Hostel Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Piece Hostel Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Piece Hostel Sanjo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Planetyze Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Poly Hostel Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Prime Inn Shinsaibashi');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Qoo Ebisucho');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Quality Hostel K''s House Tokyo Oasis');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'R.Star Hostel Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Retrometro Backpackers');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'RokuRoku');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Roots Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'RYOKAN＆HOSTEL WASABI Nippori');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Sakai Guest House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Sakura Guest House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Sakura Hostel Asakusa');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Sakura Hotel Ikebukuro');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Sakura Hotel Nippori');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Sakura La An');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Santiago Guesthouse Hiroshima');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Santiago Guesthouse Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Senba Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Sheena and Ippei');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Shell Nell namba');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Shibamata FU-TEN Bed and Local');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Shin-Osaka Tomato Guest House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Shin-Osaka Youth Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Small World Guesthouse in Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Space Hostel Tokyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Sparkling Dolphins Inn Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Stayto (former: Oak Hotel)');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Suzuki Guesthouse');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tabetoma Nijo Castle');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tabicolle Backpackers');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tadaima Japan Shinjuku Ryokan');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Talbot');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tanaka Gokurakudo Guest House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tani9 Backpackers Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'The Blend Inn');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'The Dorm Hostel Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'The Evergreen Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'THE LIFE hostel & bar lounge');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'The Lower East Nine Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'The Millennials Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'The Millennials Shibuya');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'THE NEXT DOOR lower east nine hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'The Pax Hostel/Records/More');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'The Prime Pod Ginza Tokyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'The Prime Pod Kyoto');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Toco Tokyo Heritage Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tokyo Central Youth Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tokyo Hostel ENISHI');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tokyo Hostel Fuji');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tokyo House Inn');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tokyo Hutte');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tokyo Sumidagawa Youth Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'TOKYO-W-INN Asakusa');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tomato Kyoto Station');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Tonagi Hostel × Cafe');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Train Hostel HOKUTOSEI');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Turn Table Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Umbrella House Osaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Uno Ueno');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Unplan Kagurazaka');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Very Hostel Namba');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'WeBase HAKATA');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'WIRED HOTEL Asakusa');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Wise Owl Hostels Shibuya');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Wise Owl Hostels Tokyo');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'With B');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'YADOKARI Namba Hostel');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'YADOYA Guesthouse Green');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'YADOYA Guesthouse Orange');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'YAWP! backpackers');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'You En Me House');
INSERT INTO public.hostel(id, name) values (nextval('hibernate_sequence'), 'Zabutton Hostel');
INSERT INTO public.hostel (id, name) VALUES (nextval('hibernate_sequence'), 'Ritz');
INSERT INTO public.rocket (id, name, type) VALUES (nextval('hibernate_sequence'), 'APOLLO 1', 'EXPLOSIVE');
